services:
  postgres:
    container_name: job_vacancy_postgres
    image: postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: job_vacancy
  
  sonarqube:
    container_name: sonarqube
    image: sonarqube:9.9.0-community
    environment:
      SONAR_ES_BOOTSTRAP_CHECKS_DISABLE: true
    ports:
      - 9000:9000